kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: elk
  namespace: antelope
spec:
  host: antelope.apps.vrutkovs-okd.devcluster.openshift.com
  path: /
  subdomain: ''
  to:
    kind: Service
    name: elk
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
